[platformio]
build_cache_dir = .pio/cache

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = stm32cube
build_src_filter = 
    +<../Core/Src>
    +<../Core/Inc>
build_flags =
    -ICore/Inc

upload_protocol = stlink
